### ISSUE TITLE
Failed to locate the subclass: 'Spree::Calculator::DollarAmountSalePriceCalculator'

### ISSUE THREAD

**Issue by berkes** [ronzalo/spree_sales#15]
After upgrading to the last 3-0 stable, I'm getting STI-errors: 

> An ActionView::Template::Error occurred in products#edit:
>
> The single-table inheritance mechanism failed to locate the subclass: 'Spree::Calculator::DollarAmountSalePriceCalculator'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Spree::Calculator.inheritance_column to use another column for that information.

(Same for An ActionView::Template::Error occurred in products#show)

Seems https://github.com/ronzalo/spree_sales/commit/e8a2f9f5ffe608ca675a7734653a8a18c139216b should have gotten a migration too. I'll whip one up in a PR.

**Comment by mespina** [comment]
Change existing SalePrice to ensure is belongs to a `Spree::Calculator::AmountSalePriceCalculator` instead of `Spree::Calculator::DollarAmountSalePriceCalculator`

**Comment by berkes** [comment]
@mespina That is what https://github.com/ronzalo/spree_sales/pull/16 does. But maybe I am not understanding you correctly?

**Comment by ronzalo** [comment]
@mespina @berkes this issue was solved with #16, merged into master
