### ISSUE TITLE
It must validate the sale price value

### ISSUE THREAD

**Issue by anuj-bluebash** [ronzalo/spree_sales#28]
Right now there is no validation for the sale price. From admin panel, user can add any value of sale price,and it will messed up the calculation.

For percent off  sale price should be between 0 to 1 and for amount calculator sale price value should not be greater then product original price. Here he PR for this - [https://github.com/ronzalo/spree_sales/pull/26]

**Comment by ronzalo** [comment]
Closed with https://github.com/ronzalo/spree_sales/pull/26
