### ISSUE TITLE
uninitialized constant Spree::SalesConfiguration::Config

### ISSUE THREAD

**Issue by Ajmal-hassan** [ronzalo/spree_sales#31]
rails_projects/extension/spree_sales/app/views/spree/admin/sale_prices/_form.html.erb where line #12 raised:

uninitialized constant Spree::SalesConfiguration::Config
Did you mean?  Spree::Config

I'm using rails 6 and spree 4.1.0.rc1

**Comment by berkes** [comment]
This is a duplicate of https://github.com/ronzalo/spree_sales/issues/29

**Comment by ronzalo** [comment]
Fixed on branch `4-0-stable`

**Comment by Ajmal-hassan** [comment]
Thanks
