### ISSUE TITLE
adding sale prices to all variants not working

### ISSUE THREAD

**Issue by twnaing** [ronzalo/spree_sales#33]
https://github.com/ronzalo/spree_sales/blob/9fe999cf602d962a1b966a78c47eb6d0d800d6dd/app/controllers/spree/admin/sale_prices_controller.rb#L20

https://github.com/ronzalo/spree_sales/blob/9fe999cf602d962a1b966a78c47eb6d0d800d6dd/app/models/spree/sale_price.rb#L67-L69

Should pass if variant exists or it is all_variants

```ruby
      variant = Spree::Variant.where(id: params['variant']).first || params['variant'] == 'all_variants'
      return false unless variant
```

**Comment by ronzalo** [comment]
FIxed on branch 4-0-stable
